### ISSUE TITLE
Binary exposure in MR-RAPS

### ISSUE THREAD

**Issue by coco40725** [qingyuanzhao/mr.raps#10]
Hi, 
I was wondering if we can use MR-RAPS to determine the causal effect of binary exposure on continuous outcome (or even on binary outcome). Since in this paper, you mentioned the relationship between the exposure and IVs can be **non-linear**, so is it okay that we take the summary statistics of logistic regression as the γj to do the MR-RAPS analysis?
Well, I believed that the causal estimate may be biased, but if we only want to know the causal effect is significant or not, then do you think MR-RAPS could be used  in this scenario? 
I was wondering if you could give me some advice.

**Comment by qingyuanzhao** [comment]
If the exposure is binary, you might want to use the coefficients from linear exposure vs SNP regression. Thus the estimate of the effect of the exposure on the outcome will be on the usual scale. The problem with using a logistic exposure vs SNP regression is that $\gamma_j$ then means the change in the log odds ratio of the exposure.

If you just want a test and don't care a lot about the precise meaning of the effect, I believe this is fine. The Appendix of our Annals of Statistics paper has a justification using local linear approximation and I think that applies here.
