### ISSUE TITLE
non-zero exit status and namespace issue 

### ISSUE THREAD

**Issue by AmmyDK** [qingyuanzhao/mr.raps#11]
### error report from installing mr.raps package
Hi, Qingyuan
I am trying to install the latest mr.raps package, have tried many different ways to install but obviously I cannot manage it. So I am kindly asking for some help. Many thanks. I paste the error below, and I hope to use it with the TwosampleMR package as well. 

library(devtools) 
intall_github("qingyuanzhao/mr.raps")

```
Error: package or namespace load failed for ‘mr.raps’ in namespaceExport(ns, exports):
undefined exports: calCor, getInput, grappleRobustEst, harmonise_data
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/gpfs/gpfs0/Home/ammy_p/R/x86_64-pc-linux-gnu-library/4.0/mr.raps’
* restoring previous ‘/gpfs/gpfs0/Home/ammy_p/R/x86_64-pc-linux-gnu-library/4.0/mr.raps’
Warning message:
In i.p(...) :
installation of package ‘/tmp/RtmpayF74x/file2c2b9559ab7b08/mr.raps_0.4.tar.gz’ had non-zero exit status
```

Best Regards
Ammy

**Comment by qingyuanzhao** [comment]
Updated documentation and namespace https://github.com/qingyuanzhao/mr.raps/commit/2eefa30ca10f95f1c2f2c257437a13c696173734
