### ISSUE TITLE
Error in using MR raps function

### ISSUE THREAD

**Issue by Xiaoting-Shi** [qingyuanzhao/mr.raps#12]
Hi, all! I was using TwoSampleMR package to run MR analyses where I was trying to use MR raps as one of our sensitivity analyses. However, I ran into an error message saying that there are unused arguments in my code which I don't think I've ever specified:
**Error in mr.raps::mr.raps(data, diagnostics = FALSE, over.dispersion = parameters$over.dispersion,  : 
  unused arguments (diagnostics = FALSE, shrinkage = parameters$shrinkage)**
Did anyone have solutions/thoughts to this issue? Thank you!

**Comment by qingyuanzhao** [comment]
Hi! Could you confirm the version of mr.raps you installed by executing the following command?

`sessionInfo()`

If it is the latest version (0.4.1), could you give me a minimal working example that replicates this error? Thank you.

**Comment by Xiaoting-Shi** [comment]
> Hi! Could you confirm the version of mr.raps you installed by executing the following command?
> 
> `sessionInfo()`
> 
> If it is the latest version (0.4.1), could you give me a minimal working example that replicates this error? Thank you.

Thank you for your reply! Here's the version for my relevant packages: TwoSampleMR_0.5.6   mr.raps_0.2 !
