### ISSUE TITLE
res <- mr(dat, method_list = c("mr_raps"))

### ISSUE THREAD

**Issue by Xiongqiaohua** [qingyuanzhao/mr.raps#3]
@ qingyuanzhao
     *Hello!When I was running the code`:res <- mr(dat, method_list = c("mr_raps")),`
there was an Erro**r: 'mr.raps.shrinkage' is not an exported object from 'namespace:mr.raps'.
What can i do to overcome it?Thanks for your help a lot!
       *WheI wanted to install the packges ,there was an error,two.the following is my code:
`githubinstall('mr.raps')`
Suggestion:
 - qingyuanzhao/mr.raps  R package for two-sample Mendelian randomization using the robust adjusted profile score
Do you want to install the package (Y/n)?  y
Downloading GitHub repo qingyuanzhao/mr.raps@master
Error: Failed to install 'mr.raps' from GitHub:
  incomplete block on file
I succeeded to install it with the following code successfully:
`install.packages('nortest')`
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/nortest_1.0-4.zip'
Content type 'application/zip' length 38487 bytes (37 KB)
downloaded 37 KB

package ‘nortest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\admin\AppData\Local\Temp\Rtmp8Aj2gV\downloaded_packages
>` install.packages("C:/Users/admin/Downloads/mr.raps_0.2.tar.gz", repos = NULL, type = "source")`

**Comment by qingyuanzhao** [comment]
Thank you for your questions. Please following the instructions in

https://github.com/qingyuanzhao/mr.raps/blob/master/README.md

to install the package. Let me know if you still have troubles using the software.

**Comment by Xiongqiaohua** [comment]
Thanks for your help faithfully! The problems has been solved successfully! I guess the former problems was led by the installation mode! @qingyuanzhao
