### ISSUE TITLE
Error with using mr.raps but not mr.raps.simple

### ISSUE THREAD

**Issue by zhiyu7** [qingyuanzhao/mr.raps#5]
Hi mr.raps developers, I am wondering if I could ask a technical question on using your package. I applied mr.raps for doing MR analysis through qingyuanzhao/mr.raps, where I could only ran through mr.raps.simple but not mr.raps. The error message was as listed at the end of this message. I also tried using mr(data, method_list=c("mr_raps")) of MRCIEU/TwoSampleMR and it resulted in the same error.  May I know your suggestions on how I should solve it? Many thanks! Zhi
**Error message:** 
Error in res[[i]] : subscript out of bounds
In addition: Warning messages:
1: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
2: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
3: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
4: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
5: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
6: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
7: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
8: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation
9: In matrix(0, length(z), length(p)) :
  restarting interrupted promise evaluation

**Comment by qingyuanzhao** [comment]
Thanks for raising this issue. Can you provide a reproducible example?

**Comment by zhiyu7** [comment]
Many thanks, Qingyuan! Please find below the example (mr.raps.simple can run through, but not mr.raps):
test <- data.frame("beta.exposure" = c(0.4469, 0.8371,-0.4498,0.3715,-0.6506,-0.5468,0.4456,-0.6294,-0.6651,0.5924,-0.6702,-0.1964,-0.3863,0.6983,-0.2602,-0.5724,-0.6628,0.6656,0.7582,-0.4184,-0.7852,0.752), "beta.outcome" = c(-0.0055, -0.0347,0.0109,0.0002,0.0085,0.0303,-0.0317,0.0034,0.0244,-0.0364,0.0313,0.0151,0.0133,0.0009,0.006,0.0133,0.0333,-0.021,-0.0126,0.0378,0.0441,-0.0568), "se.exposure" = c(0.0548, 0.0209,0.0722,0.0343,0.1072,0.0836,0.0637,0.097,0.0947,0.0923,0.0695,0.0293,0.03,0.0599,0.028,0.0236,0.0956,0.0678,0.0767,0.0613,0.0887,0.1155), "se.outcome"=c(0.0131, 0.0059,0.0186,0.0089,0.0271,0.0234,0.017,0.0212,0.0259,0.0224,0.0174,0.0072,0.0068,0.0154,0.0065,0.0058,0.0248,0.0171,0.0201,0.0153,0.0178,0.0288))
mr_raps_test <- mr.raps(test$beta.exposure, test$beta.outcome, test$se.exposure, test$se.outcome)
mr_raps_simple_test <- mr.raps.simple(test$beta.exposure, test$beta.outcome, test$se.exposure, test$se.outcome)

**Comment by qingyuanzhao** [comment]
`mr.raps` tries to be user-friendly and takes a data frame as input (see `?mr.raps`). So this works: `mr.raps(test)`

`mr.raps` basically calls `mr.raps.shrinkage`, which is an improvement over `mr.raps.mle`. You can also use 
`mr.raps.shrinkage(test$beta.exposure, test$beta.outcome, test$se.exposure, test$se.outcome)`
if you prefer that format. 

Please don't use `mr.raps.simple` directly unless you think you have no pleiotropy whatsoever. For more information, see `?mr.raps.mle`.

**Comment by zhiyu7** [comment]
Many thanks for your help!
