### ISSUE TITLE
Error in mr.raps(df1, diagnostics = F) : unused argument (diagnostics = F)

### ISSUE THREAD

**Issue by jjandshi** [qingyuanzhao/mr.raps#7]
> df1 = data.frame(beta.exposure = MRdat1$b.exp[indx], 
+                 beta.outcome = MRdat1$b.out[indx],
+                 se.exposure = MRdat1$se.exp[indx],
+                 se.outcome = MRdat1$se.out[indx])
> head(df1)
  beta.exposure  beta.outcome se.exposure  se.outcome
1    0.01919168  0.0016414570 0.003415616 0.001437109
2   -0.01998563  0.0009079765 0.003415616 0.001434790
3   -0.01926634  0.0006844826 0.003415616 0.001440250
4    0.01900758  0.0003900467 0.003415616 0.001434790
5   -0.03138971 -0.0018017003 0.003415616 0.001452433
6    0.01895833  0.0001865095 0.003415616 0.001434989
> res.raps1 <- mr.raps::mr.raps(df1, diagnostics=F)
Error in mr.raps::mr.raps(df1, diagnostics = F) : 
  unused argument (diagnostics = F)

**Comment by qingyuanzhao** [comment]
Could you run the function with a built-in dataset? For example,
`mr.raps(bmi.sbp)`

It is possible that you are using an old version of the package. Have you installed the latest version from GitHub?
`install_github("qingyuanzhao/mr.raps")`

**Comment by jjandshi** [comment]
It works now. Thank you and best regards!
Jiajun

**Comment by wenyc0822** [comment]
> res <-mr(mydatascz,method_list = c("mr_raps"))
Analysing 'odFUJl' on 'ENnJvO'
Error in mr.raps::mr.raps(data, diagnostics = FALSE, over.dispersion = parameters$over.dispersion,  : 
  unused arguments (diagnostics = FALSE, shrinkage = parameters$shrinkage) 
Why can't it be called from twosamplemr？？

**Comment by qingyuanzhao** [comment]
@wenyc0822 Can you try to install the latest version from GitHub?

`install_github("qingyuanzhao/mr.raps")`
