### ISSUE TITLE
Error in rho.l2(r, k, ...) : unused argument (k)

### ISSUE THREAD

**Issue by samuelejones** [qingyuanzhao/mr.raps#8]
Hey! Thanks for the awesome software - have used this extensively in my weak instrument MR analyses.

I've written some code based around your mr.raps package and have been using version 0.3.1 for a while. On a separate system, we have the latest version (0.4?) installed and my scripts no longer work.

Specifically, when running the command:

`mr.raps.shrinkage(data$beta.exposure, data$beta.outcome, data$se.exposure, data$se.outcome, over.dispersion = TRUE, loss.function = "huber", shrinkage = FALSE)`

We get the error message `Error in rho.l2(r, k, ...) : unused argument (k)`.

I assume that this is something that has changed since version 0.3.1 and 0.4, as this command worked in the older version. Am I formatting my `mr.raps.shrinkage` command incorrectly for the new version or failing to pass a parameter correctly? Or is this a bug?

**Comment by qingyuanzhao** [comment]
Closing this issue as no example was provided.
