### ISSUE TITLE
Binary outcome and logistic model

### ISSUE THREAD

**Issue by coco40725** [qingyuanzhao/mr.raps#9]
Hello! I have tried to apply this package mr.raps  into Mendelian Randomization analysis with binary outcome and continuous exposure, since in the paper you have mentioned how to estimate the causal odds ratio with this method.

However, I was wondering whether I should correct the estimate I got from mr.raps, because in the paper you said 
 β0 = β/sqrt[1 + (σ/1.7)^2], and  β0 is the estimate we obtain from mr.raps.

So, does that means if we want to get the correct estimate of causal odds ratio, we need to let β0 multipled by sqrt[1 + (σ/1.7)^2] ,
that is  **causal odds ratio = β0*sqrt[1 + (σ/1.7)^2]** ? If it is true, then how do we estimate the σ = Var (βX + ηU) ?  Do you have any suggestions?

**Comment by qingyuanzhao** [comment]
Hi! This is a really good question. This approximation formula shows that beta0 can be viewed as a lower bound for the causal odds ratio (I believe this is what most applied articles are doing and they simply treat beta0 as the causal odds ratio). We can get a better lower bound by assuming η=0. But in general, as U is unobserved, we cannot directly estimate σ = Var (βX + ηU) .
